"use client";
import type { GymOsMemberCharge,GymOsMemberPayment,PaginatedResponse } from "@gymride/types";
import { ErrorState,PageHeader,PageState,StatusBadge } from "@gymride/web-ui";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/lib/api";
import { adminMemberFinanceQuery } from "@/lib/gym-os";
const money=(v:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c}).format(v/100);
export default function AdminGymOsFinancePage(){const[gymId,setGymId]=useState(""),[search,setSearch]=useState("");const charges=useQuery({queryKey:["admin-gymos-charges",gymId,search],queryFn:()=>api.request<PaginatedResponse<GymOsMemberCharge>>(adminMemberFinanceQuery("charges",{gymId,search}))}),payments=useQuery({queryKey:["admin-gymos-payments",gymId,search],queryFn:()=>api.request<PaginatedResponse<GymOsMemberPayment>>(adminMemberFinanceQuery("payments",{gymId,search}))});return <><PageHeader eyebrow="GymOS oversight · read only" title="Member finance" description="Private gym member charges, dues, payments and receipts—not platform revenue."/><section className="panel filter-row"><input value={gymId} onChange={e=>setGymId(e.target.value)} placeholder="Gym UUID"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Member name or code"/></section>{charges.error?<ErrorState error={charges.error}/>:charges.isLoading?<PageState title="Loading charges…"/>:<section className="panel table-wrap"><h2>Charges</h2><table><thead><tr><th>Member</th><th>Membership</th><th>Fee</th><th>Paid</th><th>Outstanding</th><th>Due</th><th>Status</th></tr></thead><tbody>{charges.data?.data.map(c=><tr key={c.id}><td>{c.member?.firstName} {c.member?.lastName}</td><td>{c.membership?.planNameSnapshot}</td><td>{money(c.amountMinor,c.currency)}</td><td>{money(c.totalPaidMinor,c.currency)}</td><td>{money(c.outstandingMinor,c.currency)}</td><td>{new Date(c.dueDate).toLocaleDateString("en-IN")}</td><td><StatusBadge status={c.effectiveStatus}/></td></tr>)}</tbody></table></section>}<section className="panel table-wrap"><h2>Payments</h2><table><thead><tr><th>Receipt</th><th>Member</th><th>Amount</th><th>Method</th><th>Date</th><th>Status</th></tr></thead><tbody>{payments.data?.data.map(p=><tr key={p.id}><td>{p.receipt?.receiptNumber??"—"}</td><td>{p.member?.firstName} {p.member?.lastName}</td><td>{money(p.amountMinor,p.currency)}</td><td>{p.method}</td><td>{new Date(p.paidAt).toLocaleString("en-IN")}</td><td><StatusBadge status={p.status}/></td></tr>)}</tbody></table></section></>}
