"use client";
import { createUuid } from "@gymride/api-client";
import type { GymOsMemberCharge, GymOsMemberFinanceSummary, GymOsMemberPayment, GymSummary, PaginatedResponse } from "@gymride/types";
import { ErrorState, PageHeader, PageState, StatusBadge, pushToast, useAuth } from "@gymride/web-ui";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/lib/api";
import { canReverseGymOsPayment } from "@/lib/gym-os";
const money=(v:number,c="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:c}).format(v/100);
export default function GymOsPaymentsPage(){
 const {user}=useAuth(),canReverse=canReverseGymOsPayment(user?.roles??[]);
 const cache=useQueryClient(),[selected,setSelected]=useState(""),[search,setSearch]=useState(""),[bucket,setBucket]=useState(""),[chargeId,setChargeId]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState("UPI"),[reference,setReference]=useState(""),[reversal,setReversal]=useState("");
 const gyms=useQuery({queryKey:["gymos-finance-gyms"],queryFn:()=>api.request<PaginatedResponse<GymSummary>>("/partner/gyms?page=1&limit=100")}),gym=selected||gyms.data?.data[0]?.id||"";
 const summary=useQuery({queryKey:["gymos-finance-summary",gym],enabled:!!gym,queryFn:()=>api.request<GymOsMemberFinanceSummary>(`/partner/gyms/${gym}/gym-os/payments/summary`)});
 const charges=useQuery({queryKey:["gymos-charges",gym,search,bucket],enabled:!!gym,queryFn:()=>api.request<PaginatedResponse<GymOsMemberCharge>>(`/partner/gyms/${gym}/gym-os/charges?page=1&pageSize=100${search?`&search=${encodeURIComponent(search)}`:""}${bucket?`&dueBucket=${bucket}`:""}`)});
 const payments=useQuery({queryKey:["gymos-payments",gym],enabled:!!gym,queryFn:()=>api.request<PaginatedResponse<GymOsMemberPayment>>(`/partner/gyms/${gym}/gym-os/payments?page=1&pageSize=100`)});
 const refresh=()=>Promise.all([cache.invalidateQueries({queryKey:["gymos-finance-summary"]}),cache.invalidateQueries({queryKey:["gymos-charges"]}),cache.invalidateQueries({queryKey:["gymos-payments"]})]);
 const record=useMutation({mutationFn:()=>api.request<{receipt:{receiptNumber:string};remainingDueMinor:number}>(`/partner/gyms/${gym}/gym-os/payments`,{method:"POST",headers:{"Idempotency-Key":createUuid()},body:JSON.stringify({chargeId,amountMinor:Math.round(Number(amount)*100),method,reference:reference||undefined})}),onSuccess:async(v)=>{pushToast("Payment recorded",`${v.receipt.receiptNumber} · ${money(v.remainingDueMinor)} remaining`);setAmount("");await refresh();}});
 const reverse=useMutation({mutationFn:(id:string)=>api.request(`/partner/gyms/${gym}/gym-os/payments/${id}/reverse`,{method:"POST",body:JSON.stringify({reason:reversal})}),onSuccess:refresh});
 if(gyms.error)return <ErrorState error={gyms.error}/>;
 const metrics=summary.data?[['Collected today',summary.data.collectedTodayMinor],['This month',summary.data.collectedThisMonthMinor],['Outstanding',summary.data.outstandingMinor],['Overdue',summary.data.overdueMinor]]:[];
 return <><PageHeader eyebrow="GymOS · private member finance" title="Payments & dues" description="Record direct-member payments, monitor dues and preserve immutable receipts."/><section className="panel filter-row"><select value={gym} onChange={e=>setSelected(e.target.value)}>{gyms.data?.data.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input placeholder="Member name, code or phone" value={search} onChange={e=>setSearch(e.target.value)}/><select value={bucket} onChange={e=>setBucket(e.target.value)}><option value="">All dues</option><option value="OVERDUE">Overdue</option><option value="DUE_TODAY">Due today</option></select></section><section className="metric-grid">{metrics.map(([l,v])=><article className="metric-card" key={l}><span>{l}</span><strong>{money(Number(v))}</strong></article>)}</section>
 <section className="panel"><h2>Outstanding membership charges</h2>{charges.isLoading?<PageState title="Loading dues…"/>:charges.error?<ErrorState error={charges.error}/>:<div className="table-wrap"><table><thead><tr><th>Member</th><th>Membership</th><th>Fee</th><th>Paid</th><th>Outstanding</th><th>Due</th><th>Status</th><th>Record</th></tr></thead><tbody>{charges.data?.data.map(c=><tr key={c.id}><td>{c.member?.firstName} {c.member?.lastName}<br/><small>{c.member?.memberCode} · {c.member?.phone}</small></td><td>{c.membership?.planNameSnapshot}</td><td>{money(c.amountMinor,c.currency)}</td><td>{money(c.totalPaidMinor,c.currency)}</td><td>{money(c.outstandingMinor,c.currency)}</td><td>{new Date(c.dueDate).toLocaleDateString("en-IN")}{c.isOverdue&&<small><br/>{c.daysOverdue} days overdue</small>}</td><td><StatusBadge status={c.effectiveStatus}/></td><td>{c.outstandingMinor>0&&<button onClick={()=>{setChargeId(c.id);setAmount(String(c.outstandingMinor/100));}}>Record</button>}</td></tr>)}</tbody></table></div>}</section>
 {chargeId&&<section className="panel"><h2>Record payment</h2><div className="filter-row"><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount"/><select value={method} onChange={e=>setMethod(e.target.value)}><option>UPI</option><option>CASH</option><option>CARD</option><option>BANK_TRANSFER</option><option>CHEQUE</option><option>OTHER</option></select><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference (optional)"/><button disabled={record.isPending||!amount} onClick={()=>record.mutate()}>Confirm payment</button></div>{record.error&&<ErrorState error={record.error}/>}</section>}
 <section className="panel table-wrap"><h2>Payment history</h2>{payments.isLoading?<PageState title="Loading payments…"/>:<table><thead><tr><th>Receipt</th><th>Member</th><th>Amount</th><th>Method</th><th>Date</th><th>Reference</th><th>Status</th><th>Action</th></tr></thead><tbody>{payments.data?.data.map(p=><tr key={p.id}><td>{p.receipt?.receiptNumber??"—"}</td><td>{p.member?.firstName} {p.member?.lastName}</td><td>{money(p.amountMinor,p.currency)}</td><td>{p.method}</td><td>{new Date(p.paidAt).toLocaleString("en-IN")}</td><td>{p.reference??"—"}</td><td><StatusBadge status={p.status}/></td><td>{canReverse&&p.status==="RECORDED"&&<><input value={reversal} onChange={e=>setReversal(e.target.value)} placeholder="Reversal reason"/><button disabled={reversal.length<2} onClick={()=>reverse.mutate(p.id)}>Reverse</button></>}</td></tr>)}</tbody></table>}</section></>;
}
