ALTER TYPE "AuditAction" ADD VALUE 'GYMOS_REMINDER_RULE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'GYMOS_REMINDER_MANUAL_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE 'GYMOS_COMMUNICATION_PREFERENCE_CHANGED';
CREATE TYPE "GymOsReminderType" AS ENUM ('MEMBERSHIP_EXPIRING','MEMBERSHIP_EXPIRED','PAYMENT_DUE','PAYMENT_OVERDUE','INACTIVITY');
CREATE TYPE "GymOsReminderChannel" AS ENUM ('WHATSAPP','SMS','EMAIL');
CREATE TYPE "GymOsReminderDeliveryStatus" AS ENUM ('SCHEDULED','PROCESSING','SENT','FAILED','SKIPPED','CANCELLED');
CREATE TABLE "gym_os_reminder_rules"("id" UUID PRIMARY KEY,"gym_id" UUID NOT NULL,"type" "GymOsReminderType" NOT NULL,"channel" "GymOsReminderChannel" NOT NULL,"offset_days" INT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT false,"send_time" VARCHAR(5) NOT NULL DEFAULT '10:00',"quiet_start" VARCHAR(5) NOT NULL DEFAULT '21:00',"quiet_end" VARCHAR(5) NOT NULL DEFAULT '08:00',"last_run_at" TIMESTAMPTZ(6),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),"updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),UNIQUE("gym_id","type","channel","offset_days"));
CREATE TABLE "gym_os_member_communication_preferences"("id" UUID PRIMARY KEY,"gym_id" UUID NOT NULL,"member_id" UUID NOT NULL UNIQUE,"allow_transactional" BOOLEAN NOT NULL DEFAULT true,"allow_marketing" BOOLEAN NOT NULL DEFAULT false,"allow_whatsapp" BOOLEAN NOT NULL DEFAULT true,"allow_sms" BOOLEAN NOT NULL DEFAULT false,"allow_email" BOOLEAN NOT NULL DEFAULT false,"updated_by_user_id" UUID,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),"updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now());
CREATE TABLE "gym_os_reminder_deliveries"("id" UUID PRIMARY KEY,"gym_id" UUID NOT NULL,"member_id" UUID NOT NULL,"rule_id" UUID,"type" "GymOsReminderType" NOT NULL,"channel" "GymOsReminderChannel" NOT NULL,"subject_type" VARCHAR(40) NOT NULL,"subject_id" UUID NOT NULL,"scheduled_for" TIMESTAMPTZ(6) NOT NULL,"attempted_at" TIMESTAMPTZ(6),"sent_at" TIMESTAMPTZ(6),"status" "GymOsReminderDeliveryStatus" NOT NULL DEFAULT 'SCHEDULED',"provider" VARCHAR(40) NOT NULL DEFAULT 'development',"provider_message_id" VARCHAR(160),"attempt_count" INT NOT NULL DEFAULT 0,"last_error_code" VARCHAR(80),"dedupe_key" VARCHAR(255) NOT NULL UNIQUE,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),"updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now());
CREATE INDEX "gym_os_reminder_rules_gym_type_idx" ON "gym_os_reminder_rules"("gym_id","type");
CREATE INDEX "gym_os_preferences_gym_idx" ON "gym_os_member_communication_preferences"("gym_id");
CREATE INDEX "gym_os_deliveries_gym_scheduled_idx" ON "gym_os_reminder_deliveries"("gym_id","scheduled_for");
CREATE INDEX "gym_os_deliveries_gym_status_idx" ON "gym_os_reminder_deliveries"("gym_id","status");
CREATE INDEX "gym_os_deliveries_member_created_idx" ON "gym_os_reminder_deliveries"("member_id","created_at");
ALTER TABLE "gym_os_reminder_rules" ADD FOREIGN KEY("gym_id") REFERENCES "gyms"("id") ON DELETE RESTRICT;
ALTER TABLE "gym_os_member_communication_preferences" ADD FOREIGN KEY("gym_id") REFERENCES "gyms"("id") ON DELETE RESTRICT;
ALTER TABLE "gym_os_member_communication_preferences" ADD FOREIGN KEY("member_id") REFERENCES "gym_members"("id") ON DELETE RESTRICT;
ALTER TABLE "gym_os_reminder_deliveries" ADD FOREIGN KEY("gym_id") REFERENCES "gyms"("id") ON DELETE RESTRICT;
ALTER TABLE "gym_os_reminder_deliveries" ADD FOREIGN KEY("member_id") REFERENCES "gym_members"("id") ON DELETE RESTRICT;
ALTER TABLE "gym_os_reminder_deliveries" ADD FOREIGN KEY("rule_id") REFERENCES "gym_os_reminder_rules"("id") ON DELETE SET NULL;
